# Generated by Django 4.2.1 on 2023-07-26 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_arabic", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_arabic", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "صفحة",
                "verbose_name_plural": "صفحات",
            },
        ),
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=50)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("address_arabic", models.TextField()),
                ("description_arabic", models.TextField(blank=True, null=True)),
                ("google_map_link", models.CharField(max_length=500)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "معلومات التواصل",
                "verbose_name_plural": "معلومات التواصل",
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "نموذج التواصل",
                "verbose_name_plural": "تماذج التواصل",
            },
        ),
        migrations.CreateModel(
            name="ContactUsBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="banners/")),
            ],
            options={
                "verbose_name": "تواصل معنا",
                "verbose_name_plural": "تواصل معنا",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("name_arabic", models.CharField(max_length=50)),
                ("location_arabic", models.CharField(max_length=100)),
                ("description_arabic", models.TextField()),
                ("allow_people", models.IntegerField()),
                (
                    "size_of_restroom",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Enter in meter(s)",
                        max_digits=20,
                    ),
                ),
                (
                    "room_image",
                    models.FileField(blank=True, null=True, upload_to="room_images/"),
                ),
                ("no_of_swimming_pool", models.IntegerField(default=0)),
                ("no_of_bathroom", models.IntegerField(default=0)),
                ("no_of_bedroom", models.IntegerField(default=0)),
                ("no_of_hall", models.IntegerField(default=0)),
                ("hall_capacity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "غرفة",
                "verbose_name_plural": "غرف",
            },
        ),
        migrations.CreateModel(
            name="RoomBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="banners/")),
            ],
            options={
                "verbose_name": "صفحة الغرفة",
                "verbose_name_plural": "صفحة الغرفة",
            },
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=40)),
                ("feature_name_arabic", models.CharField(max_length=40)),
                ("icon_class", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "مميزة الغرفة",
                "verbose_name_plural": "مميزات الغرف",
            },
        ),
        migrations.CreateModel(
            name="RoomPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_price",
                        to="booking.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "سعر الغرفة",
                "verbose_name_plural": "اسعار الغرف",
            },
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(blank=True, max_length=4, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "selected_dates",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("selected_date", models.DateField(blank=True, null=True)),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_booking",
                        to="booking.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حجز غرفة",
                "verbose_name_plural": "حجوزات الغرف",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="feature",
            field=models.ManyToManyField(to="booking.roomfeature"),
        ),
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="banners/")),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="booking.banner",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحة الصور",
                "verbose_name_plural": "صفحة الصور",
            },
        ),
    ]
