# Generated by Django 4.2.1 on 2023-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
