# Generated by Django 4.2.1 on 2023-06-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_roombooking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_booking', to='booking.room'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_price', to='booking.room'),
        ),
    ]
