# Generated by Django 4.2.1 on 2023-08-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_roombooking_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "Banner", "verbose_name_plural": "Banners"},
        ),
        migrations.AlterModelOptions(
            name="bannerimage",
            options={
                "verbose_name": "Banner Image",
                "verbose_name_plural": "Banner Images",
            },
        ),
        migrations.AlterModelOptions(
            name="contactdetails",
            options={
                "verbose_name": "Contact Details",
                "verbose_name_plural": "Contact Details",
            },
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "verbose_name": "Contact Form",
                "verbose_name_plural": "Contact Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="contactusbanner",
            options={
                "verbose_name": "Contact Us Banner",
                "verbose_name_plural": "Contact Us Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="roombanner",
            options={
                "verbose_name": "Room Banner",
                "verbose_name_plural": "Room Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="roombooking",
            options={
                "verbose_name": "Room Booking",
                "verbose_name_plural": "Room Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="roomfeature",
            options={
                "verbose_name": "Room Feature",
                "verbose_name_plural": "Room Features",
            },
        ),
        migrations.AlterModelOptions(
            name="roomprice",
            options={
                "verbose_name": "Room Price",
                "verbose_name_plural": "Room Prices",
            },
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="snapchat",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
    ]
