# Generated by Django 4.2.2 on 2023-06-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_roombooking_room_alter_roomprice_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roombooking",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="roombooking",
            name="start_date",
        ),
        migrations.AddField(
            model_name="roombooking",
            name="selected_dates",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
