# Generated by Django 4.2.1 on 2023-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_roombooking_email_roombooking_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='no_of_beds',
            field=models.IntegerField(default=0),
        ),
    ]
