# Generated by Django 4.2.2 on 2023-06-10 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_remove_roombooking_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="booking_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
