# Generated by Django 4.2.1 on 2023-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_no_of_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomfeature',
            name='feature_name_arabic',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
