# Generated by Django 4.2.1 on 2023-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_roombooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
