# Generated by Django 4.2.1 on 2023-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_room_hall_capacity_room_no_of_bathroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_image",
            field=models.FileField(blank=True, null=True, upload_to="room_images/"),
        ),
    ]
