# Generated by Django 4.2.1 on 2023-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_congratulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='special_event',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
