# Generated by Django 4.2.1 on 2023-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_roombooking_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprice',
            name='special_price',
            field=models.IntegerField(default=0),
        ),
    ]
