# Generated by Django 4.2.1 on 2023-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_alter_banner_options_alter_bannerimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description_arabic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_arabic",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="address_arabic",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="description_arabic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="email_arabic",
            field=models.EmailField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="fax_arabic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="phone_number_arabic",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="email_arabic",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="message_arabic",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="name_arabic",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactform",
            name="phone_number_arabic",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="description_arabic",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="location_arabic",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="name_arabic",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomfeature",
            name="feature_name_arabic",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
    ]
