# Generated by Django 4.2.1 on 2023-09-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_roomprice_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomfeature',
            name='sequence',
            field=models.SmallIntegerField(default=0),
        ),
    ]
