# Generated by Django 4.2.1 on 2023-07-18 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_banner_description_arabic_banner_title_arabic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactdetails",
            name="email_arabic",
        ),
        migrations.RemoveField(
            model_name="contactdetails",
            name="fax_arabic",
        ),
        migrations.RemoveField(
            model_name="contactdetails",
            name="phone_number_arabic",
        ),
    ]
