# Generated by Django 4.2.1 on 2023-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_roomfeature_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='age',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
