# Generated by Django 4.2.1 on 2023-07-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0012_alter_banner_options_alter_bannerimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="selected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
