# Generated by Django 4.2.1 on 2023-07-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_contactform_email_arabic_and_more'),
        ('booking', '0013_roombooking_selected_date'),
    ]

    operations = [
    ]
